# Generated by Django 3.1 on 2020-08-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='image',
            name='local_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Example.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
