# Generated by Django 3.1 on 2020-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0004_auto_20200825_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='local_file',
            new_name='original_image',
        ),
        migrations.AddField(
            model_name='image',
            name='resized_image',
            field=models.ImageField(default='NULL', upload_to='images/resized'),
            preserve_default=False,
        ),
    ]
